{{- if and .Values.tempo.enabled .Values.tempo.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.tempo.name "type" "tracing" "context" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tempo.persistence.size }}
  {{- if .Values.tempo.persistence.storageClass }}
  storageClassName: {{ .Values.tempo.persistence.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}

