{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.gateway.name "type" "application" "context" .) | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.gateway.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.gateway.service.type "NodePort") .Values.gateway.service.nodePort }}
    nodePort: {{ .Values.gateway.service.nodePort }}
    {{- end }}
  selector:
    {{- include "observability-stack.componentSelectorLabels" (dict "component" .Values.gateway.name "context" .) | nindent 4 }}
{{- end }}