{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.otelCollector.name }}
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.otelCollector.name "type" "telemetry" "context" .) | nindent 4 }}
{{- end }}

