{{- if and .Values.loki.enabled .Values.loki.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.loki.name "type" "logging" "context" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.persistence.size }}
  {{- if .Values.loki.persistence.storageClass }}
  storageClassName: {{ .Values.loki.persistence.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}

