{{- if and .Values.promtail.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.promtail.name }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.promtail.name "type" "logging" "context" .) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.promtail.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.promtail.name }}
  namespace: {{ include "observability-stack.namespace" . }}
{{- end }}
