{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.promtail.name }}
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.promtail.name "type" "logging" "context" .) | nindent 4 }}
{{- end }}

