{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.promtail.name "type" "logging" "context" .) | nindent 4 }}
data:
  config.yml: |
    server:
      {{- with .Values.promtail.config.server }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

    positions:
      {{- with .Values.promtail.config.positions }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

    clients:
      {{- range .Values.promtail.config.clients }}
      - url: {{ .url }}
      {{- end }}

    scrape_configs:
      {{- range .Values.promtail.config.scrape_configs }}
      - job_name: {{ .job_name }}
        {{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
          {{- toYaml .kubernetes_sd_configs | nindent 10 }}
        {{- end }}
        {{- if .relabel_configs }}
        relabel_configs:
          {{- toYaml .relabel_configs | nindent 10 }}
        {{- end }}
        {{- if .pipeline_stages }}
        pipeline_stages:
          {{- toYaml .pipeline_stages | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end }}