{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.componentLabels" (dict "component" .Values.grafana.name "type" "visualization" "context" .) | nindent 4 }}
{{- end }}